"""Replace navbar.js CSS block with minimal popup-only CSS"""
with open('navbar.js', 'r', encoding='utf-8') as f:
    content = f.read()

css_start = content.find("var css = [\n")
css_block_begin = content.index('[', css_start) + 1
css_end = content.index("\n  ].join('\\n');", css_block_begin)

minimal_css = '''
    ':root {',
    '  --gn-popup-bg: #ffffff;',
    '  --gn-popup-alt: #f5f6f8;',
    '  --gn-popup-border: #e2e6ed;',
    '}',
    '[data-theme="light"] {',
    '  --gn-popup-bg: #ffffff;',
    '  --gn-popup-alt: #f5f6f8;',
    '  --gn-popup-border: #e2e6ed;',
    '}',
    'body.gn-transitioning { opacity: 1; transition: none; }',
    'html[data-role="operator"] .role-manager:not(.role-operator) { display: none !important; }',
    'html[data-role="operator"] .role-developer:not(.role-operator) { display: none !important; }',
    'html[data-role="manager"] .role-developer:not(.role-manager) { display: none !important; }',
    '.gn-degrade-popup {',
    '  position: fixed; top: 50%%; left: 50%%; transform: translate(-50%%,-50%%) scale(0.95);',
    '  width: 440px; max-width: 94vw; max-height: 84vh; overflow-y: auto;',
    '  background: var(--gn-popup-bg); border: 1px solid var(--gn-popup-border);',
    '  border-radius: 12px; box-shadow: 0 24px 64px rgba(0,0,0,0.15);',
    '  z-index: 9999; padding: 28px 32px 24px; font-size: 13px;',
    '  color: var(--gn-text-secondary, #4a5568); line-height: 1.6;',
    '  opacity: 0; pointer-events: none;',
    '  transition: opacity 0.2s ease-out, transform 0.2s ease-out;',
    '}',
    '.gn-degrade-popup.show { opacity: 1; pointer-events: auto; transform: translate(-50%%,-50%%) scale(1); }',
    '.gn-degrade-overlay {',
    '  position: fixed; inset: 0; background: rgba(0,0,0,0.35);',
    '  backdrop-filter: blur(2px); z-index: 9998;',
    '  opacity: 0; pointer-events: none; transition: opacity 0.2s ease-out;',
    '}',
    '.gn-degrade-overlay.show { opacity: 1; pointer-events: auto; }',
    '.gn-degrade-popup .dg-header {',
    '  display: flex; align-items: center; gap: 10px; margin-bottom: 20px;',
    '  padding-bottom: 16px; border-bottom: 1px solid var(--gn-popup-border);',
    '}',
    '.gn-degrade-popup .dg-header-icon {',
    '  width: 36px; height: 36px; border-radius: 10px; flex-shrink: 0;',
    '  display: flex; align-items: center; justify-content: center;',
    '}',
    '.gn-degrade-popup .dg-header-icon svg { width: 20px; height: 20px; }',
    '.gn-degrade-popup .dg-title { font-size: 15px; font-weight: 600; color: var(--gn-text, #1a1d26); }',
    '.gn-degrade-popup .dg-subtitle { font-size: 11px; color: var(--gn-text-muted, #7a8498); }',
    '.gn-degrade-popup .dg-section { margin-bottom: 16px; }',
    '.gn-degrade-popup .dg-section-label {',
    '  font-size: 10px; font-weight: 600; text-transform: uppercase;',
    '  letter-spacing: 0.05em; color: var(--gn-text-muted, #7a8498); margin-bottom: 8px;',
    '}',
    '.gn-degrade-popup .dg-module {',
    '  display: flex; align-items: center; justify-content: space-between;',
    '  padding: 10px 14px; margin-bottom: 4px;',
    '  background: var(--gn-popup-alt); border-radius: 8px;',
    '}',
    '.gn-degrade-popup .dg-module-name { font-size: 13px; font-weight: 500; color: var(--gn-text, #1a1d26); }',
    '.gn-degrade-popup .dg-module-status {',
    '  display: inline-flex; align-items: center; gap: 6px;',
    '  font-size: 12px; font-weight: 500; padding: 3px 10px; border-radius: 6px;',
    '}',
    '.gn-degrade-popup .dg-module-status.ok { background: rgba(63,185,80,0.08); color: #2d8a3e; }',
    '.gn-degrade-popup .dg-module-status.fail { background: rgba(240,68,68,0.08); color: #c0392b; }',
    '.gn-degrade-popup .dg-module-status svg { width: 14px; height: 14px; }',
    '.gn-degrade-popup .dg-desc {',
    '  font-size: 12px; color: var(--gn-text-secondary, #4a5568);',
    '  padding: 12px 14px; background: var(--gn-popup-alt);',
    '  border-radius: 8px; border-left: 3px solid var(--gn-popup-border); line-height: 1.7;',
    '}',
    '.gn-degrade-popup .dg-desc code {',
    '  display: block; margin-top: 4px; padding: 6px 10px;',
    '  background: rgba(0,0,0,0.04); border: 1px solid var(--gn-popup-border); border-radius: 4px;',
    '  font-family: var(--font-mono, monospace); font-size: 11px;',
    '  color: var(--gn-text-secondary, #4a5568); word-break: break-all;',
    '}',
    '.gn-degrade-popup .dg-close {',
    '  position: absolute; top: 16px; right: 16px; width: 28px; height: 28px;',
    '  border-radius: 8px; border: none; background: transparent;',
    '  color: var(--gn-text-muted, #7a8498); cursor: pointer;',
    '  display: flex; align-items: center; justify-content: center;',
    '  transition: background 0.15s, color 0.15s;',
    '}',
    '.gn-degrade-popup .dg-close:hover { background: var(--gn-popup-alt); color: var(--gn-text, #1a1d26); }',\n'''

content = content[:css_block_begin] + minimal_css + content[css_end:]

with open('navbar.js', 'w', encoding='utf-8') as f:
    f.write(content)
print(f'Navbar JS slimmed. New size: {len(content)} bytes')
